package com.uit.entity;
// Generated May 20, 2019 1:05:38 AM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * AppRole generated by hbm2java
 */
@Entity
@Table(name = "app_role", catalog = "news_database", uniqueConstraints = @UniqueConstraint(columnNames = "role_name"))
public class AppRole implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 9145035666305553142L;
	private int roleId;
	private String roleName;
	private Set<AppUser> appUsers = new HashSet<AppUser>(0);

	public AppRole() {
	}
	
	
	
	public AppRole(String roleName) {
		super();
		this.roleName = roleName;
	}



	public AppRole(String roleName, Set<AppUser> appUsers) {
		super();
		this.roleName = roleName;
		this.appUsers = appUsers;
	}



	public AppRole(int roleId, String roleName) {
		this.roleId = roleId;
		this.roleName = roleName;
	}

	public AppRole(int roleId, String roleName, Set<AppUser> appUsers) {
		this.roleId = roleId;
		this.roleName = roleName;
		this.appUsers = appUsers;
	}

	@Id
	@GeneratedValue
	@Column(name = "role_id", unique = true, nullable = false)
	public int getRoleId() {
		return this.roleId;
	}

	public void setRoleId(int roleId) {
		this.roleId = roleId;
	}

	@Column(name = "role_name", unique = true, nullable = false, length = 50)
	public String getRoleName() {
		return this.roleName;
	}

	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "appRole")
	public Set<AppUser> getAppUsers() {
		return this.appUsers;
	}

	public void setAppUsers(Set<AppUser> appUsers) {
		this.appUsers = appUsers;
	}

}
