package com.uit.entity;
// Generated Apr 22, 2019 1:25:12 AM by Hibernate Tools 5.1.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Category generated by hbm2java
 */
@Entity
@Table(name = "category", catalog = "news_database")
public class Category implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1338602033335243054L;
	private Integer id;
	private String categoryName;
	private Set<News> newses = new HashSet<News>(0);

	public Category() {
	}

	public Category(String categoryName, Set<News> newses) {
		this.categoryName = categoryName;
		this.newses = newses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "category_name")
	public String getCategoryName() {
		return this.categoryName;
	}

	public void setCategoryName(String categoryName) {
		this.categoryName = categoryName;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "category")
	public Set<News> getNewses() {
		return this.newses;
	}

	public void setNewses(Set<News> newses) {
		this.newses = newses;
	}

}
