package com.uit.entity;
// Generated May 20, 2019 1:05:38 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Priority generated by hbm2java
 */
@Entity
@Table(name = "priority", catalog = "news_database")
public class Priority implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -2377646968968926792L;
	private int priorityId;

	public Priority() {
	}

	public Priority(int priorityId) {
		this.priorityId = priorityId;
	}

	@Id

	@Column(name = "priority_id", unique = true, nullable = false)
	public int getPriorityId() {
		return this.priorityId;
	}

	public void setPriorityId(int priorityId) {
		this.priorityId = priorityId;
	}

}
