package com.uit.entity;
// Generated May 20, 2019 1:05:38 AM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Tag generated by hbm2java
 */
@Entity
@Table(name = "tag", catalog = "news_database", uniqueConstraints = @UniqueConstraint(columnNames = "tag_name"))
public class Tag implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5060924809600759364L;
	private int tagId;
	private String tagName;
	private String url;
	private Set<News> newses = new HashSet<News>(0);

	public Tag() {
	}

	public Tag(int tagId, String tagName, String url) {
		super();
		this.tagId = tagId;
		this.tagName = tagName;
		this.url = url;
	}

	public Tag(String tagName) {
		super();
		this.tagName = tagName;
	}

	public Tag(int tagId, String tagName) {
		this.tagId = tagId;
		this.tagName = tagName;
	}

	public Tag(int tagId, String tagName, Set<News> newses) {
		this.tagId = tagId;
		this.tagName = tagName;
		this.newses = newses;
	}

	@Id
	@GeneratedValue
	@Column(name = "tag_id", unique = true, nullable = false)
	public int getTagId() {
		return this.tagId;
	}

	public void setTagId(int tagId) {
		this.tagId = tagId;
	}

	@Column(name = "tag_name", unique = true, nullable = false, length = 20)
	public String getTagName() {
		return this.tagName;
	}

	public void setTagName(String tagName) {
		this.tagName = tagName;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "tags")
	public Set<News> getNewses() {
		return this.newses;
	}

	public void setNewses(Set<News> newses) {
		this.newses = newses;
	}

	@Column(name = "url", nullable = false, length = 100)
	public String getUrl() {
		return url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

}
